pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln' 
    msbuildArgs: '/p:DeployExtension=false'

